name: Shellcheck
on: [push, pull_request]
jobs:
    shellcheck:
    runs-on: ubuntu-latest
    steps:
    - users: actions/checkout@v4
    - name: Run Shellcheck
      users: ludeeus/action-shellcheck@v1
      with:
        args: "scripts/*.sh"
